# Generated by Django 6.0.4 on 2026-10-05 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0002_organization_alter_order_payment_status_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='shipping_policy', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMCostTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='Gemini', max_length=50)),
                ('model_name', models.CharField(default='gemini-3.6-flash', max_length=100)),
                ('operation', models.CharField(default='CopilotQuery', max_length=100)),
                ('tokens_used', models.IntegerField(default=350)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.00035, max_digits=8)),
                ('latency_ms', models.IntegerField(default=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='quality_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_score',
            field=models.IntegerField(default=85),
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(default='long_term_preference', max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPassport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_code', models.CharField(max_length=100, unique=True)),
                ('artisan_verified', models.BooleanField(default=True)),
                ('material_declaration', models.CharField(default='100% Genuine Artisan Material', max_length=255)),
                ('origin_declaration', models.CharField(default='Rajasthan, India', max_length=255)),
                ('sustainability_rating', models.CharField(default='A+ Eco-Friendly Handcrafted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='artisan_api.product')),
            ],
        ),
    ]
