# Generated by Django 6.0.4 on 2026-10-05 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0003_businessknowledge_llmcosttracker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('risk_level', models.CharField(default='READ', max_length=30)),
                ('input_summary', models.JSONField(default=dict)),
                ('result_summary', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentIdentity',
            fields=[
                ('agent_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=150)),
                ('scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ai_readiness_score',
            field=models.IntegerField(default=92),
        ),
        migrations.AddField(
            model_name='product',
            name='verification_state',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('declared', 'Declared by Artisan'), ('org_verified', 'Organization Verified'), ('platform_verified', 'Platform Verified')], default='org_verified', max_length=30),
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='artisan_api.agentidentity')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessGoalPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.CharField(max_length=255)),
                ('plan_steps', models.JSONField(default=list)),
                ('status', models.CharField(default='proposed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('session_id', models.CharField(max_length=100)),
                ('is_committed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='artisan_api.product')),
            ],
        ),
    ]
