# Generated by Django 6.0.4 on 2026-10-05 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0005_eventexhibitionmode_aitask_approvalinboxitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='assigned_agent',
            field=models.CharField(default='Catalog Agent', max_length=100),
        ),
        migrations.AddField(
            model_name='approvalinboxitem',
            name='preview_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='approvalinboxitem',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='approvalinboxitem',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='approvalinboxitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_items', to='artisan_api.aitask'),
        ),
        migrations.AddField(
            model_name='eventexhibitionmode',
            name='event_name',
            field=models.CharField(default='Craft Fair Event', max_length=255),
        ),
        migrations.AddField(
            model_name='eventexhibitionmode',
            name='event_products',
            field=models.ManyToManyField(blank=True, related_name='events', to='artisan_api.product'),
        ),
        migrations.AddField(
            model_name='eventexhibitionmode',
            name='qr_code_slug',
            field=models.CharField(default='event-qr', max_length=100),
        ),
        migrations.AddField(
            model_name='eventexhibitionmode',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='smartsupportticket',
            name='customer_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='smartsupportticket',
            name='suggested_resolution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aitask',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalinboxitem',
            name='artisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_inbox_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalinboxitem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='approvalinboxitem',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='eventexhibitionmode',
            name='name',
            field=models.CharField(default='Craft Fair Event', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventexhibitionmode',
            name='qr_code_ref',
            field=models.CharField(default='event-ref', max_length=100),
        ),
        migrations.AlterField(
            model_name='smartsupportticket',
            name='customer_name',
            field=models.CharField(default='Valued Customer', max_length=150),
        ),
    ]
