# Generated by Django 6.0.4 on 2026-10-05 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0006_aitask_assigned_agent_approvalinboxitem_preview_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_log', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=1)),
                ('status', models.CharField(default='FAILED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyAIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('developer_name', models.CharField(default='Ecosystem Developer', max_length=150)),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('pricing_model', models.CharField(default='FREE', max_length=30)),
                ('required_scopes', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=4.85, max_digits=3)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketExpansionExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_market', models.CharField(default='UAE', max_length=50)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='artisan_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_type', models.CharField(choices=[('ARTISAN', 'Artisan'), ('CUSTOMER', 'Customer'), ('ORGANIZATION', 'Organization'), ('MARKETPLACE', 'Marketplace'), ('AI_AGENT', 'AI Agent'), ('DEVELOPER', 'Developer'), ('PARTNER', 'Partner')], default='ARTISAN', max_length=30)),
                ('trust_level', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('BASIC_VERIFIED', 'Basic Verified'), ('ORGANIZATION_VERIFIED', 'Organization Verified'), ('PLATFORM_VERIFIED', 'Platform Verified')], default='BASIC_VERIFIED', max_length=30)),
                ('trust_signals', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('provenance_sources', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='artisan_api.product')),
            ],
        ),
    ]
