# Generated by Django 6.0.4 on 2026-10-05 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0007_deadletterqueueitem_thirdpartyaiagent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILearningStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_title', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('action_taken', models.CharField(max_length=255)),
                ('expected_outcome', models.CharField(max_length=255)),
                ('actual_outcome', models.CharField(default='Pending Evaluation', max_length=255)),
                ('source', models.CharField(choices=[('OBSERVED', 'Observed'), ('DERIVED', 'Derived'), ('USER_FEEDBACK', 'User Feedback'), ('EXPERIMENT', 'Experiment'), ('EXTERNAL_DATA', 'External Data'), ('AI_GENERATED', 'AI Generated')], default='EXPERIMENT', max_length=30)),
                ('is_successful', models.BooleanField(default=True)),
                ('impact_delta', models.CharField(default='+0.0%', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSearchGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_query', models.CharField(max_length=255, unique=True)),
                ('query_count', models.IntegerField(default=1)),
                ('category_hint', models.CharField(default='Pottery & Craft', max_length=100)),
                ('suggested_artisan_action', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_key', models.CharField(max_length=100)),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('template_text', models.TextField()),
                ('status', models.CharField(default='PRODUCTION', max_length=20)),
                ('evaluation_score', models.DecimalField(decimal_places=2, default=94.5, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIPromptExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experiment_name', models.CharField(max_length=255)),
                ('metrics_a', models.JSONField(blank=True, default=dict)),
                ('metrics_b', models.JSONField(blank=True, default=dict)),
                ('winning_variant', models.CharField(default='VARIANT_A', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments_a', to='artisan_api.promptversion')),
                ('variant_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments_b', to='artisan_api.promptversion')),
            ],
        ),
    ]
