# Generated by Django 6.0.4 on 2026-10-05 14:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0008_ailearningstore_productsearchgap_promptversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, default='default-tenant', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_metric', models.CharField(default='REVENUE', max_length=100)),
                ('target_value', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=18450.0, max_digits=12)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('autonomy_level', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('achieved', 'Achieved'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('risk_level', models.CharField(default='MEDIUM', max_length=20)),
                ('required_permissions', models.JSONField(blank=True, default=list)),
                ('success_metrics', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='in_progress', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='artisan_api.businessgoal')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(max_length=100)),
                ('entity_type', models.CharField(default='product', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('confidence', models.FloatField(default=0.85)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAIBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('orders_count', models.IntegerField(default=12)),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=18450.0, max_digits=10)),
                ('needs_attention', models.JSONField(blank=True, default=list)),
                ('opportunity_text', models.TextField(blank=True, default='')),
                ('suggested_action', models.TextField(blank=True, default='')),
                ('pending_approvals_count', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_briefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(default='Commerce Decision Engine', max_length=100)),
                ('model_name', models.CharField(default='gemini-3.6-flash', max_length=100)),
                ('input_context_ref', models.CharField(blank=True, default='', max_length=255)),
                ('retrieved_evidence', models.JSONField(blank=True, default=list)),
                ('candidate_actions', models.JSONField(blank=True, default=list)),
                ('selected_action', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.88)),
                ('risk_assessment', models.CharField(default='MEDIUM', max_length=30)),
                ('policy_evaluation', models.JSONField(blank=True, default=dict)),
                ('approval_required', models.BooleanField(default=True)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('outcome_measurement', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_traces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opportunity_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('entity_type', models.CharField(default='product', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.88)),
                ('expected_impact', models.CharField(default='+15% Conversion', max_length=255)),
                ('urgency', models.CharField(default='HIGH', max_length=20)),
                ('possible_actions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('evaluating', 'Evaluating'), ('plan_ready', 'Plan Ready'), ('approved', 'Approved'), ('executing', 'Executing'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='discovered', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
