# Generated by Django 6.0.4 on 2026-10-05 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0009_businessgoal_aiplan_businesssignal_dailyaibrief_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Clay', max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=65.0, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('moq', models.IntegerField(default=10)),
                ('stock_available', models.IntegerField(default=500)),
                ('lead_time_days', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Terracotta & Raw Clay', max_length=100)),
                ('materials_provided', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(default='Jaipur, Rajasthan', max_length=150)),
                ('lead_time_days', models.IntegerField(default=4)),
                ('moq', models.IntegerField(default=25)),
                ('unit_price', models.DecimalField(decimal_places=2, default=450.0, max_digits=10)),
                ('quality_rating', models.DecimalField(decimal_places=2, default=4.85, max_digits=3)),
                ('reliability_score', models.IntegerField(default=96)),
                ('payment_terms', models.CharField(default='Net 30 Days', max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='B2BBuyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Heritage Craft Boutique Retail', max_length=255)),
                ('buyer_type', models.CharField(default='RETAIL_STORE', max_length=50)),
                ('tax_id', models.CharField(blank=True, default='GSTIN08AAACH1234F1Z5', max_length=100)),
                ('shipping_address', models.TextField(default='Bandra Kurla Complex, Mumbai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_required', models.DecimalField(decimal_places=2, default=2.5, max_digits=8)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=65.0, max_digits=10)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='artisan_api.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisan_api.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('product_category', models.CharField(default='Handcrafted Corporate Gifts', max_length=100)),
                ('quantity', models.IntegerField(default=1000)),
                ('target_unit_price', models.DecimalField(decimal_places=2, default=750.0, max_digits=10)),
                ('deadline_days', models.IntegerField(default=25)),
                ('customization_requirements', models.TextField(blank=True, default='Blue silk packaging with company logo embossing')),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QualityControlCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(default='PRODUCTION_INSPECTION', max_length=50)),
                ('status', models.CharField(default='PASSED', max_length=30)),
                ('inspector_notes', models.TextField(blank=True, default='Zero hairline cracks. Uniform pigment density verified.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_checkpoints', to='artisan_api.requestforquote')),
            ],
        ),
        migrations.CreateModel(
            name='B2BQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_or_collective', models.CharField(default='Jaipur Artisan Collective', max_length=255)),
                ('offered_unit_price', models.DecimalField(decimal_places=2, default=720.0, max_digits=10)),
                ('lead_time_days', models.IntegerField(default=20)),
                ('moq', models.IntegerField(default=100)),
                ('customization_notes', models.TextField(blank=True, default='Hand-embossed logo included with natural clay finish')),
                ('status', models.CharField(default='SUBMITTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='artisan_api.requestforquote')),
            ],
        ),
        migrations.CreateModel(
            name='SplitOrderAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artisan_group_name', models.CharField(default='Jaipur Craft Group', max_length=255)),
                ('allocated_quantity', models.IntegerField(default=350)),
                ('unit_payout', models.DecimalField(decimal_places=2, default=650.0, max_digits=10)),
                ('status', models.CharField(default='IN_PRODUCTION', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='artisan_api.requestforquote')),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='artisan_api.supplier'),
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=65.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=3250.0, max_digits=10)),
                ('status', models.CharField(default='ORDERED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan_api.supplier')),
            ],
        ),
    ]
