# Generated by Django 6.0.4 on 2026-10-05 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0010_rawmaterial_supplier_b2bbuyerprofile_billofmaterials_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceKnowledgeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=10)),
                ('category', models.CharField(default='Packaging & Labeling', max_length=100)),
                ('requirement_summary', models.TextField()),
                ('source_title', models.CharField(default='Official Customs & Trade Portal', max_length=255)),
                ('source_url', models.CharField(default='https://customs.gov', max_length=255)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('scope', models.CharField(default='HANDICRAFTS_CERAMICS', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarketProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=10, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('shipping_carriers', models.JSONField(blank=True, default=list)),
                ('regulatory_summary', models.TextField(blank=True, default='')),
                ('compliance_confidence', models.FloatField(default=0.92)),
                ('official_source_url', models.CharField(blank=True, default='https://trade.gov', max_length=255)),
                ('freshness_status', models.CharField(default='FRESH', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportReadinessScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_country', models.CharField(default='DE', max_length=10)),
                ('readiness_status', models.CharField(default='PARTIALLY_READY', max_length=30)),
                ('readiness_breakdown', models.JSONField(blank=True, default=dict)),
                ('missing_items', models.JSONField(blank=True, default=list)),
                ('action_plan', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_scorecards', to='artisan_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCommerceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_country', models.CharField(default='India', max_length=100)),
                ('business_region', models.CharField(default='Rajasthan', max_length=100)),
                ('preferred_currencies', models.JSONField(blank=True, default=list)),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('export_readiness_score', models.IntegerField(default=85)),
                ('shipping_capabilities', models.JSONField(blank=True, default=dict)),
                ('accepted_payment_methods', models.JSONField(blank=True, default=list)),
                ('documentation_status', models.CharField(default='PARTIALLY_READY', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_commerce_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeDocumentWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(default='COMMERCIAL_INVOICE', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('reference_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='VERIFIED', max_length=30)),
                ('content_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
