# Generated by Django 6.0.4 on 2026-10-05 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0011_complianceknowledgerule_marketprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAttributionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=100)),
                ('source_type', models.CharField(default='AI_AGENT', max_length=30)),
                ('action_type', models.CharField(max_length=50)),
                ('gmv_impact', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentNegotiationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_agent_id', models.CharField(default='buyer_agent_01', max_length=100)),
                ('seller_agent_id', models.CharField(default='seller_agent_01', max_length=100)),
                ('rfq_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('offers_history', models.JSONField(blank=True, default=list)),
                ('agreement_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentToolDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('required_scopes', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(default='READ', max_length=30)),
                ('status', models.CharField(default='PUBLISHED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentPurchasePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_order_value', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10)),
                ('requires_confirmation_above', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('daily_budget_limit', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('allowed_categories', models.JSONField(blank=True, default=list)),
                ('allowed_merchants', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_purchase_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
