# Generated by Django 6.0.4 on 2026-10-05 18:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0012_agentattributionlog_agentnegotiationsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('topic_category', models.CharField(default='Craft Education', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_private', models.BooleanField(default=False)),
                ('member_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_communities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('post_type', models.CharField(default='QUESTION', max_length=50)),
                ('verified_answer_flag', models.BooleanField(default=False)),
                ('status', models.CharField(default='PUBLISHED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='artisan_api.community')),
            ],
        ),
        migrations.CreateModel(
            name='ContentAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='AI Social Content Draft', max_length=255)),
                ('content_type', models.CharField(default='instagram_post', max_length=50)),
                ('channel', models.CharField(default='instagram', max_length=50)),
                ('script_text', models.TextField(blank=True, default='')),
                ('visual_storyboard', models.JSONField(blank=True, default=list)),
                ('caption', models.TextField(blank=True, default='')),
                ('version', models.IntegerField(default=1)),
                ('prompt_version', models.CharField(default='v1.0', max_length=20)),
                ('factuality_status', models.CharField(default='VERIFIED_GROUNDED', max_length=50)),
                ('price_consistency_status', models.CharField(default='VALIDATED', max_length=50)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_assets', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_assets', to='artisan_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ContentCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Artisan Campaign', max_length=255)),
                ('objective', models.CharField(default='Diwali Handmade Gifting Campaign', max_length=255)),
                ('target_audience', models.CharField(default='Eco-Conscious & Craft Admirers', max_length=255)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('budget', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('estimated_reach', models.IntegerField(default=15000)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('content_themes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_campaigns', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_content_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(default='instagram', max_length=50)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='scheduled', max_length=30)),
                ('publication_logs', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='artisan_api.contentasset')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='artisan_api.contentcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirements', models.TextField(blank=True, default='Create 1 Unboxing Video + 1 Instagram Reel highlighting craft process')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('fixed_compensation', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('status', models.CharField(default='INVITED', max_length=30)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_creator_collaborations', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_links', to='artisan_api.contentcampaign')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_collaborations', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='artisan_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Artisan Creator', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('categories', models.JSONField(blank=True, default=list)),
                ('audience_languages', models.JSONField(blank=True, default=list)),
                ('content_style', models.CharField(default='Storytelling & Unboxing', max_length=100)),
                ('approved_metrics', models.JSONField(blank=True, default=dict)),
                ('public_portfolio', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='SCHEDULED', max_length=30)),
                ('viewer_count', models.IntegerField(default=0)),
                ('product_showcase', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_referrals', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payout_status', models.CharField(default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan_api.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan_api.product')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan_api.referral')),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True, default='')),
                ('craft_story', models.TextField(blank=True, default='')),
                ('craft_region', models.CharField(default='Rajasthan, India', max_length=100)),
                ('verified_info', models.JSONField(blank=True, default=dict)),
                ('public_visibility', models.BooleanField(default=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
