# Generated by Django 6.0.4 on 2026-10-05 18:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0013_community_communitypost_contentasset_contentcampaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Packaging', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='APPROVED', max_length=30)),
                ('cost_center', models.CharField(default='Operations', max_length=100)),
                ('ai_confidence', models.FloatField(default=0.95)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(max_length=100)),
                ('severity', models.CharField(default='HIGH', max_length=30)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('affected_entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(default='Price Adjustment Simulation', max_length=255)),
                ('price_change_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cost_change_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('shipping_change_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('volume_change_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estimated_revenue_impact', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_margin_impact', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_type', models.CharField(default='B2C', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='ISSUED', max_length=30)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(default='SALE', max_length=50)),
                ('reference_type', models.CharField(default='ORDER', max_length=50)),
                ('reference_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('direction', models.CharField(default='CREDIT', max_length=10)),
                ('category', models.CharField(default='Revenue', max_length=100)),
                ('status', models.CharField(default='POSTED', max_length=30)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformBillingMeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_plan', models.CharField(default='GROWTH', max_length=50)),
                ('total_llm_tokens', models.IntegerField(default=142000)),
                ('total_ai_cost', models.DecimalField(decimal_places=2, default=28.4, max_digits=10)),
                ('api_calls_count', models.IntegerField(default=1240)),
                ('billing_cycle_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_meter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marketplace_name', models.CharField(default='Amazon Handmade', max_length=100)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='MATCHED', max_length=30)),
                ('mismatch_reason', models.CharField(blank=True, default='', max_length=255)),
                ('settlement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
