# Generated by Django 6.0.4 on 2026-10-05 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0014_expense_financialanomaly_financialscenario_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISOP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Support', max_length=100)),
                ('sop_code', models.CharField(default='SOP-001', max_length=50)),
                ('content', models.TextField()),
                ('structured_steps', models.JSONField(blank=True, default=list)),
                ('source_authority', models.CharField(default='Human Manager', max_length=100)),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AITeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mission', models.TextField()),
                ('team_roles', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('current_spend', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('team_memory', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='SPECIALIST', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('agent_type', models.CharField(default='DIGITAL_EMPLOYEE', max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('autonomy_level', models.IntegerField(default=2)),
                ('system_instructions', models.TextField(blank=True, default='')),
                ('goals', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('tool_scopes', models.JSONField(blank=True, default=dict)),
                ('memory_scope', models.CharField(default='BUSINESS_MEMORY', max_length=100)),
                ('knowledge_scope', models.JSONField(blank=True, default=list)),
                ('approval_policy', models.JSONField(blank=True, default=dict)),
                ('risk_policy', models.CharField(default='MEDIUM', max_length=30)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('current_spend', models.DecimalField(decimal_places=2, default=42.5, max_digits=10)),
                ('certification_status', models.CharField(default='CERTIFIED', max_length=30)),
                ('version', models.CharField(default='v1.0', max_length=30)),
                ('performance_score', models.FloatField(default=94.5)),
                ('reliability_score', models.FloatField(default=96.0)),
                ('accuracy_score', models.FloatField(default=95.0)),
                ('tasks_completed_count', models.IntegerField(default=34)),
                ('tasks_failed_count', models.IntegerField(default=1)),
                ('human_corrections_count', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_employees', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_employees', to='artisan_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WorkforceIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(max_length=100)),
                ('severity', models.CharField(default='HIGH', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='RESOLVED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_incidents', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='artisan_api.digitalemployee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkforceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(default='ANALYSIS', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('goal', models.TextField()),
                ('priority', models.CharField(default='NORMAL', max_length=20)),
                ('status', models.CharField(default='QUEUED', max_length=30)),
                ('input_context', models.JSONField(blank=True, default=dict)),
                ('output_result', models.JSONField(blank=True, default=dict)),
                ('shared_memory', models.JSONField(blank=True, default=dict)),
                ('handoff_chain', models.JSONField(blank=True, default=list)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(default='MEDIUM', max_length=20)),
                ('approval_required', models.BooleanField(default=False)),
                ('approval_status', models.CharField(default='NOT_REQUIRED', max_length=30)),
                ('approval_reason', models.TextField(blank=True, default='')),
                ('cost_budget', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='artisan_api.digitalemployee')),
                ('sop_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan_api.aisop')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='artisan_api.aiteam')),
            ],
        ),
    ]
