# Generated by Django 6.0.4 on 2026-10-05 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0015_aisop_aiteam_digitalemployee_workforceincident_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Access Control', max_length=100)),
                ('status', models.CharField(default='IMPLEMENTED', max_length=30)),
                ('evidence_summary', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('provider', models.CharField(default='Google DeepMind', max_length=100)),
                ('purpose', models.CharField(default='REASONING', max_length=100)),
                ('privacy_level', models.CharField(default='HIGH', max_length=50)),
                ('approval_status', models.CharField(default='APPROVED', max_length=30)),
                ('version_pinned', models.CharField(default='2026-v1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToolTrustRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(default='MEDIUM', max_length=20)),
                ('data_scope', models.CharField(default='INTERNAL', max_length=50)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('require_human_approval', models.BooleanField(default=False)),
                ('max_calls_per_hour', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=100)),
                ('status', models.CharField(default='GRANTED', max_length=30)),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='FINANCIAL', max_length=100)),
                ('scope', models.CharField(default='TENANT', max_length=50)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('effect', models.CharField(default='REQUIRE_APPROVAL', max_length=30)),
                ('priority', models.IntegerField(default=10)),
                ('version', models.CharField(default='v1.0', max_length=30)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(default='AI_AGENT', max_length=50)),
                ('actor_id', models.CharField(blank=True, default='system', max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(default='HIGH', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='RESOLVED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
