# Generated by Django 6.0.4 on 2026-10-05 19:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0016_governancecontrol_modelregistry_tooltrustrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='CAMPAIGN_STRATEGY', max_length=100)),
                ('decision_summary', models.TextField()),
                ('rationale_and_evidence', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.CharField(default='Business Manager', max_length=100)),
                ('actual_outcome', models.TextField(blank=True, default='')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.92, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_memories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeConflictRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('source_a_name', models.CharField(max_length=255)),
                ('source_a_value', models.CharField(max_length=255)),
                ('source_b_name', models.CharField(max_length=255)),
                ('source_b_value', models.CharField(max_length=255)),
                ('preferred_source', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='DETECTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeGapRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('demand_score', models.CharField(default='HIGH', max_length=20)),
                ('current_coverage_pct', models.DecimalField(decimal_places=2, default=35.0, max_digits=5)),
                ('recommended_action', models.TextField()),
                ('assigned_owner', models.CharField(default='Compliance Specialist', max_length=100)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_gaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeGraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('entity_id_ref', models.CharField(blank=True, default='', max_length=100)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('trust_level', models.CharField(default='VERIFIED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeGraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=100)),
                ('confidence', models.CharField(default='HIGH', max_length=30)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='artisan_api.knowledgegraphnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='artisan_api.knowledgegraphnode')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(default='SOP', max_length=100)),
                ('trust_level', models.CharField(default='VERIFIED', max_length=50)),
                ('classification', models.CharField(default='INTERNAL', max_length=50)),
                ('owner', models.CharField(default='Operations Team', max_length=100)),
                ('version', models.CharField(default='v1.0', max_length=30)),
                ('freshness_status', models.CharField(default='FRESH', max_length=30)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('uri_or_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('knowledge_type', models.CharField(default='FACT', max_length=100)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('confidence_level', models.CharField(default='HIGH', max_length=30)),
                ('freshness_status', models.CharField(default='FRESH', max_length=30)),
                ('classification', models.CharField(default='INTERNAL', max_length=50)),
                ('version', models.CharField(default='v1.0', max_length=30)),
                ('status', models.CharField(default='APPROVED', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_objects', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_objects', to='artisan_api.knowledgesource')),
            ],
        ),
    ]
