# Generated by Django 6.0.4 on 2026-10-05 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0017_decisionmemory_knowledgeconflictrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwinSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_name', models.CharField(default='Live Business State Snapshot', max_length=255)),
                ('snapshot_type', models.CharField(default='DAILY', max_length=50)),
                ('cash_position_inr', models.DecimalField(decimal_places=2, default=184500.0, max_digits=12)),
                ('inventory_value_inr', models.DecimalField(decimal_places=2, default=94200.0, max_digits=12)),
                ('active_orders_count', models.IntegerField(default=18)),
                ('production_capacity_units', models.IntegerField(default=500)),
                ('workforce_capacity_pct', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('twin_health_score', models.IntegerField(default=94)),
                ('state_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_twin_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(max_length=255)),
                ('category', models.CharField(default='CAMPAIGN', max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('duration_days', models.IntegerField(default=30)),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_scenarios', to=settings.AUTH_USER_MODEL)),
                ('baseline_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='artisan_api.digitaltwinsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioCalibration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_revenue_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_revenue_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forecast_error_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calibration_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_calibrations', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='artisan_api.businessscenario')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projected_revenue_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('revenue_delta_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('projected_margin_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('margin_delta_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('projected_cash_impact_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('inventory_delta_units', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='LOW', max_length=20)),
                ('strategic_score', models.IntegerField(default=82)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.88, max_digits=5)),
                ('sensitivity_drivers', models.JSONField(blank=True, default=list)),
                ('assumptions_summary', models.JSONField(blank=True, default=list)),
                ('uncertainties', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_result', to='artisan_api.businessscenario')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyCouncilReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finance_agent_perspective', models.TextField(blank=True, default='')),
                ('growth_agent_perspective', models.TextField(blank=True, default='')),
                ('supply_agent_perspective', models.TextField(blank=True, default='')),
                ('risk_agent_perspective', models.TextField(blank=True, default='')),
                ('consensus_recommendation', models.TextField()),
                ('reversibility', models.CharField(default='REVERSIBLE', max_length=30)),
                ('requires_human_approval', models.BooleanField(default=True)),
                ('approval_status', models.CharField(default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_reviews', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_reviews', to='artisan_api.businessscenario')),
            ],
        ),
    ]
