# Generated by Django 6.0.4 on 2026-10-06 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0018_digitaltwinsnapshot_businessscenario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHypothesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('treatment_variable', models.CharField(max_length=255)),
                ('outcome_variable', models.CharField(max_length=255)),
                ('predicted_direction', models.CharField(default='INCREASE', max_length=20)),
                ('rationale', models.TextField()),
                ('prior_confidence', models.DecimalField(decimal_places=2, default=0.65, max_digits=5)),
                ('impact_score', models.IntegerField(default=85)),
                ('status', models.CharField(default='PROPOSED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hypotheses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnknown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('business_impact', models.CharField(default='HIGH', max_length=20)),
                ('cost_to_learn', models.CharField(default='LOW', max_length=20)),
                ('value_of_information_score', models.IntegerField(default=88)),
                ('recommended_experiment', models.TextField()),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_unknowns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CausalExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('experiment_type', models.CharField(default='AB_TEST', max_length=50)),
                ('treatment_definition', models.JSONField(blank=True, default=dict)),
                ('control_definition', models.JSONField(blank=True, default=dict)),
                ('target_population', models.CharField(default='Eligible Returning Customers', max_length=255)),
                ('primary_metric', models.CharField(default='Conversion Rate', max_length=100)),
                ('secondary_metrics', models.JSONField(blank=True, default=list)),
                ('guardrail_metrics', models.JSONField(blank=True, default=dict)),
                ('sample_size_treatment', models.IntegerField(default=500)),
                ('sample_size_control', models.IntegerField(default=500)),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causal_experiments', to=settings.AUTH_USER_MODEL)),
                ('hypothesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='artisan_api.businesshypothesis')),
            ],
        ),
        migrations.CreateModel(
            name='CausalRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cause_node', models.CharField(max_length=255)),
                ('effect_node', models.CharField(max_length=255)),
                ('relationship_type', models.CharField(default='INFLUENCES', max_length=50)),
                ('evidence_level', models.CharField(default='E2_OBSERVATIONAL', max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('estimated_effect_size', models.CharField(default='+12.4% Lift', max_length=255)),
                ('context_payload', models.JSONField(blank=True, default=dict)),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causal_relationships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_metric_value', models.DecimalField(decimal_places=4, default=4.2, max_digits=10)),
                ('treatment_metric_value', models.DecimalField(decimal_places=4, default=4.8, max_digits=10)),
                ('absolute_lift', models.DecimalField(decimal_places=4, default=0.6, max_digits=10)),
                ('relative_lift_pct', models.DecimalField(decimal_places=2, default=14.29, max_digits=7)),
                ('confidence_interval_low', models.DecimalField(decimal_places=2, default=3.1, max_digits=7)),
                ('confidence_interval_high', models.DecimalField(decimal_places=2, default=12.5, max_digits=7)),
                ('p_value', models.DecimalField(decimal_places=4, default=0.024, max_digits=6)),
                ('bayesian_win_probability', models.DecimalField(decimal_places=2, default=0.94, max_digits=5)),
                ('incremental_revenue_inr', models.DecimalField(decimal_places=2, default=18500.0, max_digits=12)),
                ('guardrails_passed', models.BooleanField(default=True)),
                ('evidence_level', models.CharField(default='E5_CONTROLLED_EXP', max_length=50)),
                ('analysis_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_results', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='artisan_api.causalexperiment')),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeLearning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('learning_summary', models.TextField()),
                ('context_constraints', models.JSONField(blank=True, default=dict)),
                ('evidence_level', models.CharField(default='E5_CONTROLLED_EXP', max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.9, max_digits=5)),
                ('is_stale', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_learnings', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learnings', to='artisan_api.causalexperiment')),
            ],
        ),
    ]
