# Generated by Django 6.0.4 on 2026-10-06 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0019_businesshypothesis_businessunknown_causalexperiment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('competitor_type', models.CharField(default='DIRECT', max_length=50)),
                ('category', models.CharField(default='Pottery & Handicrafts', max_length=100)),
                ('observed_pricing_range', models.CharField(default='₹999 - ₹2,499', max_length=100)),
                ('market_positioning', models.CharField(default='Mass Premium Craft Decor', max_length=255)),
                ('observed_channels', models.JSONField(blank=True, default=list)),
                ('last_observed_move', models.TextField(blank=True, default='Reduced Jaipur Pottery Vase price by 12% for festive promotion.')),
                ('last_observed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(default='OFFICIAL_API', max_length=50)),
                ('url_identifier', models.CharField(blank=True, default='', max_length=500)),
                ('authority_score', models.DecimalField(decimal_places=2, default=0.9, max_digits=5)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=0.88, max_digits=5)),
                ('freshness_status', models.CharField(default='FRESH', max_length=30)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='PRODUCT', max_length=50)),
                ('urgency', models.CharField(default='IMMEDIATE', max_length=30)),
                ('opportunity_score', models.IntegerField(default=88)),
                ('estimated_revenue_potential_inr', models.DecimalField(decimal_places=2, default=125000.0, max_digits=12)),
                ('required_resources', models.TextField(blank=True, default='Existing pottery workshop capacity + ₹5,000 custom packaging.')),
                ('why_now_reason', models.TextField(blank=True, default='Festive corporate gifting demand surged +35% with low competitor personalization.')),
                ('opportunity_window_months', models.IntegerField(default=3)),
                ('status', models.CharField(default='DETECTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketThreat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('threat_type', models.CharField(default='COMPETITOR_PRICING', max_length=50)),
                ('severity', models.CharField(default='MEDIUM', max_length=20)),
                ('impact_description', models.TextField()),
                ('recommended_defensive_strategy', models.TextField()),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_threats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Home & Living', max_length=100)),
                ('trend_status', models.CharField(default='GROWING', max_length=30)),
                ('velocity_score', models.DecimalField(decimal_places=2, default=0.82, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.88, max_digits=5)),
                ('evidence_sources_count', models.IntegerField(default=4)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_trends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
