# Generated by Django 6.0.4 on 2026-10-06 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0020_competitorprofile_intelligencesource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCapacityResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(default='PRODUCTION', max_length=50)),
                ('available_units_per_week', models.IntegerField(default=1000)),
                ('utilization_rate_pct', models.DecimalField(decimal_places=2, default=45.0, max_digits=5)),
                ('location_region', models.CharField(default='Jaipur, Rajasthan', max_length=100)),
                ('is_available_for_pooling', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_capacities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDemandPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pool_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(default='Ceramics & Decor', max_length=100)),
                ('aggregated_units', models.IntegerField(default=1100)),
                ('participating_buyers_count', models.IntegerField(default=4)),
                ('target_delivery_days', models.IntegerField(default=25)),
                ('target_unit_price_inr', models.DecimalField(decimal_places=2, default=450.0, max_digits=10)),
                ('feasibility_status', models.CharField(default='FEASIBLE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_demand_pools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkEcosystemOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(default='GROUP_PROCUREMENT', max_length=50)),
                ('match_score', models.IntegerField(default=92)),
                ('estimated_economic_value_inr', models.DecimalField(decimal_places=2, default=495000.0, max_digits=12)),
                ('participating_nodes_summary', models.TextField(blank=True, default='18 Artisans + 3 Raw Material Suppliers + 2 Logistics Networks')),
                ('why_now_reason', models.TextField(blank=True, default='High B2B buyer demand pool aligned with 55% unused artisan pottery capacity.')),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkEntityGraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=100, unique=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(default='ARTISAN', max_length=50)),
                ('verification_status', models.CharField(default='VERIFIED', max_length=30)),
                ('location_region', models.CharField(default='Jaipur, Rajasthan, India', max_length=100)),
                ('capabilities', models.TextField(blank=True, default='Blue Pottery, Handcrafting, Direct B2B Fulfillment')),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.92, max_digits=5)),
                ('privacy_consent_level', models.CharField(default='OPT_IN_AGGREGATE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMultiPartyMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_title', models.CharField(max_length=255)),
                ('match_score', models.IntegerField(default=95)),
                ('matched_buyers_summary', models.CharField(default='4 Corporate B2B Buyers (Pooled Demand: 5,000 units)', max_length=255)),
                ('matched_artisans_summary', models.CharField(default='Jaipur Artisan Cluster (25 Artisans, 5,600 units capacity)', max_length=255)),
                ('matched_suppliers_summary', models.CharField(default='Silk Craft Dyes & Terracotta Clay Supplies', max_length=255)),
                ('matched_logistics_summary', models.CharField(default='Express Logistics Regional Network', max_length=255)),
                ('status', models.CharField(default='RECOMMENDED', max_length=30)),
                ('provenance_receipt', models.TextField(blank=True, default='Verified deterministic constraint solver + trust policy validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkRelationshipEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(default='SUPPLIES', max_length=50)),
                ('strength_weight', models.DecimalField(decimal_places=2, default=0.85, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata_info', models.TextField(blank=True, default='Active procurement & fulfillment edge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_edges', to=settings.AUTH_USER_MODEL)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='artisan_api.networkentitygraphnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='artisan_api.networkentitygraphnode')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSignalMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(default='DEMAND_SURGE', max_length=50)),
                ('source_category', models.CharField(default='B2B_RFQ_AGGREGATION', max_length=100)),
                ('category', models.CharField(default='Handicrafts & Decor', max_length=100)),
                ('location_scope', models.CharField(default='Northern India Region', max_length=100)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.91, max_digits=5)),
                ('privacy_level', models.CharField(default='AGGREGATED_ANONYMOUS', max_length=30)),
                ('payload_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_signals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
