# Generated by Django 6.0.4 on 2026-10-06 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0021_networkcapacityresource_networkdemandpool_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCommerceMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(default='EXPLICIT_PREFERENCE', max_length=50)),
                ('memory_key', models.CharField(default='festive_eco_gift_preference', max_length=100)),
                ('memory_value', models.TextField(default='Customer prefers eco-friendly handmade gifts under ₹2,000 for festival occasions.')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.94, max_digits=5)),
                ('provenance_source', models.CharField(default='USER_EXPLICIT_INPUT', max_length=100)),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerConsentPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_personalization', models.BooleanField(default=True)),
                ('allow_ai_memory', models.BooleanField(default=True)),
                ('allow_recommendations', models.BooleanField(default=True)),
                ('allow_behavioral_analytics', models.BooleanField(default=True)),
                ('allow_voice_vision_search', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPreferenceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_categories', models.CharField(default='Ceramics & Decor, Home Living, Festive Gifts', max_length=255)),
                ('preferred_price_min_inr', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('preferred_price_max_inr', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10)),
                ('preferred_materials', models.CharField(default='Organic Terracotta, Cobalt Blue Glaze, Silk', max_length=255)),
                ('preferred_languages', models.CharField(default='Hindi, English', max_length=100)),
                ('gift_intent_frequency', models.CharField(default='HIGH', max_length=50)),
                ('inferred_style', models.CharField(default='Authentic Traditional & Modern Heritage', max_length=100)),
                ('privacy_mode', models.CharField(default='STANDARD', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_360_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingSessionIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_query', models.TextField(default='Mujhe 2000 ke andar sister ke birthday ke liye handmade unique gift chahiye.')),
                ('intent_type', models.CharField(default='GIFT_SHOPPING', max_length=50)),
                ('extracted_category', models.CharField(default='Handmade Gift Sets', max_length=100)),
                ('budget_max_inr', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('target_delivery_days', models.IntegerField(default=5)),
                ('recipient_type', models.CharField(default='Sister', max_length=50)),
                ('occasion', models.CharField(default='Birthday', max_length=50)),
                ('extracted_constraints_json', models.TextField(default='{"style": "unique", "material": "handmade ceramic/clay"}')),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_intents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerShortlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shortlist_name', models.CharField(default='Birthday Gift Shortlist', max_length=255)),
                ('personal_fit_score', models.IntegerField(default=94)),
                ('fit_explanation', models.TextField(default='Handmade authentic terracotta vase within your ₹2,000 budget with 4-day express delivery.')),
                ('tradeoffs_summary', models.TextField(default='Fragile material requires standard craft packaging; high customer rating (4.9/5).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_shortlists', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='artisan_api.product')),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan_api.shoppingsessionintent')),
            ],
        ),
    ]
