# Generated by Django 6.0.4 on 2026-10-06 09:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0022_customercommercememory_customerconsentpreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='National Heritage Handloom & Craft Expo', max_length=255)),
                ('event_type', models.CharField(default='CRAFT_FAIR', max_length=50)),
                ('city', models.CharField(default='New Delhi', max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('participating_artisans_json', models.TextField(default='["artisan_1", "artisan_2"]')),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineSyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(default='MOBILE_DEVICE_77', max_length=100)),
                ('event_type', models.CharField(default='OFFLINE_QR_SCAN', max_length=50)),
                ('payload_json', models.TextField(default='{}')),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('idempotency_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('store_type', models.CharField(default='PERMANENT', max_length=50)),
                ('address', models.TextField(default='Main Artisan Hub, Craft Lane')),
                ('city', models.CharField(default='Jaipur', max_length=100)),
                ('region', models.CharField(default='Rajasthan', max_length=100)),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('operating_hours', models.CharField(default='10:00 AM - 08:00 PM IST', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('capabilities_json', models.TextField(default='{"pickup": true, "qr_enabled": true, "kiosk_enabled": true, "staff_copilot": true}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('qr_type', models.CharField(default='PRODUCT_QR', max_length=50)),
                ('resolution_target_url', models.URLField(default='https://artisancommerce.os/qr/resolve')),
                ('scans_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan_api.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan_api.store')),
            ],
        ),
        migrations.CreateModel(
            name='PickupReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('pickup_code', models.CharField(default='PICKUP-9821', max_length=20)),
                ('status', models.CharField(default='RESERVED', max_length=30)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_window_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_reservations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisan_api.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_reservations', to='artisan_api.store')),
            ],
        ),
        migrations.CreateModel(
            name='OmnichannelSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(default='WEB', max_length=50)),
                ('session_token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('context_json', models.TextField(default='{"active_intent": "Browsing", "last_qr_scanned": null}')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omnichannel_sessions', to=settings.AUTH_USER_MODEL)),
                ('current_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan_api.store')),
            ],
        ),
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kiosk_device_id', models.CharField(default='KIOSK_JAIPUR_01', max_length=100)),
                ('session_token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('active_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_sessions', to='artisan_api.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_available', models.IntegerField(default=15)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=3)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventories', to='artisan_api.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='artisan_api.store')),
            ],
        ),
    ]
