# Generated by Django 6.0.4 on 2026-10-06 10:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0023_exhibitionevent_offlinesyncqueue_store_qrasset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('status', models.CharField(default='ONLINE', max_length=30)),
                ('local_queue_count', models.IntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_gateways', to='artisan_api.store')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReconciliationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pos_count', models.IntegerField(default=18)),
                ('system_count', models.IntegerField(default=15)),
                ('sensor_count', models.IntegerField(default=17)),
                ('confidence_score', models.FloatField(default=0.88)),
                ('discrepancy_reason', models.TextField(default='Possible un-scanned POS return or misplaced shelf stock.')),
                ('recommended_action', models.TextField(default='Schedule physical audit task for Shelf 3 and adjust system inventory count to 17.')),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisan_api.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='artisan_api.store')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('device_type', models.CharField(default='SCANNER', max_length=50)),
                ('manufacturer', models.CharField(default='Zebra Technologies', max_length=100)),
                ('model_name', models.CharField(default='DS2208 Handheld Scanner', max_length=100)),
                ('firmware_version', models.CharField(default='v2.4.1', max_length=50)),
                ('status', models.CharField(default='ONLINE', max_length=30)),
                ('trust_level', models.CharField(default='HIGH', max_length=30)),
                ('capabilities_json', models.TextField(default='["scanner", "barcode_reader"]')),
                ('health_score', models.IntegerField(default=95)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_devices', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='artisan_api.store')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEventTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(default='ScanReceived', max_length=50)),
                ('payload_json', models.TextField(default='{}')),
                ('confidence_score', models.FloatField(default=0.95)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_events', to='artisan_api.physicaldevice')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommandLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(default='physical_ops_agent_01', max_length=100)),
                ('command_name', models.CharField(default='display_product', max_length=100)),
                ('parameters_json', models.TextField(default='{}')),
                ('risk_level', models.CharField(default='LOW', max_length=30)),
                ('approval_status', models.CharField(default='APPROVED', max_length=30)),
                ('execution_result_json', models.TextField(default='{"status": "SUCCESS"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='artisan_api.physicaldevice')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalStoreTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(default='SHELF_RESTOCK', max_length=50)),
                ('title', models.CharField(default='Restock Terracotta Lamp on Shelf 2', max_length=255)),
                ('description', models.TextField(default='Smart shelf sensor detected stock level below 4 units. Restock 10 units from Jaipur backroom.')),
                ('priority', models.CharField(default='HIGH', max_length=30)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='artisan_api.store')),
            ],
        ),
        migrations.CreateModel(
            name='SensorInventorySignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_quantity', models.IntegerField(default=14)),
                ('previous_quantity', models.IntegerField(default=15)),
                ('confidence_score', models.FloatField(default=0.92)),
                ('calibration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_signals', to='artisan_api.physicaldevice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisan_api.product')),
            ],
        ),
    ]
