# Generated by Django 6.0.4 on 2026-10-06 14:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0024_edgegateway_inventoryreconciliationreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSecurityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(default='catalog_agent_01', max_length=100, unique=True)),
                ('autonomy_level', models.IntegerField(default=2)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('allowed_tools_json', models.TextField(default='["update_catalog", "read_inventory"]')),
                ('max_tool_calls_per_minute', models.IntegerField(default=30)),
                ('prompt_injection_shield_active', models.BooleanField(default=True)),
                ('last_security_audit', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Suspicious Payment Velocity & New Device Context', max_length=255)),
                ('category', models.CharField(default='PAYMENT_FRAUD', max_length=100)),
                ('severity', models.CharField(default='HIGH', max_length=30)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('affected_actor_id', models.CharField(default='customer_user_01', max_length=100)),
                ('risk_score', models.IntegerField(default=85)),
                ('confidence_score', models.FloatField(default=0.94)),
                ('evidence_summary', models.TextField(default='Rapid 4 orders within 90 seconds from unrecognized IP reference.')),
                ('recommended_containment', models.TextField(default='Require Step-Up 2FA verification and temporarily freeze auto-payout.')),
                ('containment_status', models.CharField(default='STEP_UP_VERIFICATION_REQUIRED', max_length=50)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(default='High Value Payment Step-Up Verification Policy', max_length=255)),
                ('category', models.CharField(default='PAYMENT_RISK', max_length=100)),
                ('actor_scope', models.CharField(default='ALL', max_length=50)),
                ('risk_threshold', models.IntegerField(default=75)),
                ('effect', models.CharField(default='CHALLENGE', max_length=30)),
                ('conditions_json', models.TextField(default='{"transaction_amount_gt": 10000, "new_device": true}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_value', models.CharField(default='198.51.100.44', max_length=255)),
                ('indicator_type', models.CharField(default='IP_ADDRESS', max_length=50)),
                ('category', models.CharField(default='BOTNET_ANOMALY', max_length=100)),
                ('confidence_score', models.FloatField(default=0.88)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='securityevent',
            name='artisan',
        ),
        migrations.RemoveField(
            model_name='securityevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='securityevent',
            name='details',
        ),
        migrations.AddField(
            model_name='securityevent',
            name='confidence_score',
            field=models.FloatField(default=0.92),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='device_reference',
            field=models.CharField(default='DEV_SIM_001', max_length=100),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='ip_reference',
            field=models.CharField(default='198.51.100.44', max_length=50),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='resource_id',
            field=models.CharField(default='ORD_9901', max_length=100),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='resource_type',
            field=models.CharField(default='ORDER', max_length=100),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='risk_signals_json',
            field=models.TextField(default='["unusual_ip", "new_device_context"]'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='session_reference',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='source',
            field=models.CharField(default='API_GATEWAY', max_length=100),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='tenant_id',
            field=models.CharField(default='default_tenant', max_length=100),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='actor_id',
            field=models.CharField(default='customer_user_01', max_length=100),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='actor_type',
            field=models.CharField(default='CUSTOMER', max_length=50),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(default='LOGIN_ATTEMPT', max_length=100),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='severity',
            field=models.CharField(default='MEDIUM', max_length=30),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='status',
            field=models.CharField(default='PROCESSED', max_length=30),
        ),
    ]
