# Generated by Django 6.0.4 on 2026-10-06 14:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0026_securityevent_artisan_securityevent_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreakerRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(default='Primary LLM Gateway', max_length=100, unique=True)),
                ('state', models.CharField(default='CLOSED', max_length=20)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_state_change', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FailureEventRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(default='default_tenant', max_length=100)),
                ('service', models.CharField(default='Unified Ledger & Payments', max_length=100)),
                ('failure_type', models.CharField(default='PAYMENT_PROVIDER_TIMEOUT', max_length=100)),
                ('severity', models.CharField(default='HIGH', max_length=30)),
                ('symptoms', models.TextField(default='Provider timeout after 5000ms')),
                ('affected_resources_json', models.TextField(default='["ORD_9901"]')),
                ('status', models.CharField(default='FLAGGED', max_length=30)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Resilience Incident: Payment Provider Timeout', max_length=255)),
                ('category', models.CharField(default='PAYMENT', max_length=50)),
                ('severity', models.CharField(default='HIGH', max_length=30)),
                ('status', models.CharField(default='INVESTIGATING', max_length=30)),
                ('affected_service', models.CharField(default='Unified Ledger & Payments', max_length=100)),
                ('impact_summary', models.TextField(default='Primary payment gateway timed out.')),
                ('rto_target_minutes', models.IntegerField(default=2)),
                ('rpo_target_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(default='Commerce API Gateway', max_length=100)),
                ('category', models.CharField(default='API', max_length=50)),
                ('status', models.CharField(default='HEALTHY', max_length=30)),
                ('latency_ms', models.IntegerField(default=14)),
                ('error_rate_pct', models.FloatField(default=0.01)),
                ('criticality', models.CharField(default='CRITICAL', max_length=20)),
                ('rto_minutes', models.IntegerField(default=1)),
                ('rpo_minutes', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryPlanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_title', models.CharField(default='Failover to Secondary Payment Gateway', max_length=255)),
                ('recovery_action', models.CharField(default='SWITCH_PAYMENT_GATEWAY', max_length=100)),
                ('target_resource', models.CharField(default='PG_SECONDARY', max_length=100)),
                ('risk_score', models.IntegerField(default=15)),
                ('requires_approval', models.BooleanField(default=False)),
                ('status', models.CharField(default='RECOMMENDED', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plans', to='artisan_api.operationalincident')),
            ],
        ),
    ]
