# Generated by Django 6.0.4 on 2026-10-06 14:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0027_circuitbreakerrecord_failureeventrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='High P95 Latency Anomaly', max_length=255)),
                ('service', models.CharField(default='Checkout & Order API', max_length=150)),
                ('severity', models.CharField(default='HIGH', max_length=30)),
                ('category', models.CharField(default='LATENCY', max_length=50)),
                ('correlated_incident_id', models.CharField(blank=True, default='', max_length=100)),
                ('deduplicated_count', models.IntegerField(default=1)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RunbookRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Database Connection Contention Mitigation', max_length=255)),
                ('service', models.CharField(default='Checkout & Order API', max_length=150)),
                ('category', models.CharField(default='DATABASE', max_length=50)),
                ('symptoms', models.TextField(default='Postgres connection pool exhaustion and elevated P95 latency.')),
                ('safe_checks_json', models.TextField(default='["Inspect pg_stat_activity", "Check active pool usage"]')),
                ('recovery_actions_json', models.TextField(default='["Switch read-traffic to read replicas", "Scale worker pool"]')),
                ('requires_four_eyes_approval', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=12)),
                ('success_rate_pct', models.FloatField(default=98.5)),
                ('version', models.CharField(default='v1.4', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDefinitionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.CharField(default='svc_checkout_api', max_length=100, unique=True)),
                ('name', models.CharField(default='Checkout & Order API', max_length=255)),
                ('owner', models.CharField(default='Anita Sharma (Staff SRE)', max_length=150)),
                ('team', models.CharField(default='Commerce Core Platform', max_length=150)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('criticality', models.CharField(default='TIER_0', max_length=30)),
                ('status', models.CharField(default='HEALTHY', max_length=30)),
                ('latency_ms', models.IntegerField(default=112)),
                ('error_rate', models.FloatField(default=0.08)),
                ('traffic_rpm', models.IntegerField(default=4500)),
                ('saturation_pct', models.FloatField(default=42.5)),
                ('dependencies_json', models.TextField(default='[]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLORecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Checkout Availability (99.9%)', max_length=255)),
                ('service_name', models.CharField(default='Checkout & Order API', max_length=150)),
                ('target_pct', models.FloatField(default=99.9)),
                ('current_pct', models.FloatField(default=99.94)),
                ('measurement_window', models.CharField(default='30d', max_length=50)),
                ('error_budget_remaining_pct', models.FloatField(default=60.0)),
                ('burn_rate', models.FloatField(default=0.8)),
                ('status', models.CharField(default='MET', max_length=30)),
                ('owner', models.CharField(default='Commerce Core Platform', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SRETraceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(default=uuid.uuid4, max_length=100)),
                ('user_goal', models.CharField(default='Artisan Product AI Catalog Generation', max_length=255)),
                ('flow_steps_json', models.TextField(default='[]')),
                ('total_latency_ms', models.IntegerField(default=480)),
                ('llm_token_count', models.IntegerField(default=14200)),
                ('llm_cost_usd', models.FloatField(default=0.0426)),
                ('tool_call_count', models.IntegerField(default=8)),
                ('has_bottleneck', models.BooleanField(default=False)),
                ('bottleneck_stage', models.CharField(default='NONE', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryEventRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(default='default_tenant', max_length=100)),
                ('service', models.CharField(default='Checkout & Order API', max_length=100)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('event_type', models.CharField(default='METRIC', max_length=50)),
                ('trace_id', models.CharField(blank=True, default='', max_length=100)),
                ('span_id', models.CharField(blank=True, default='', max_length=100)),
                ('severity', models.CharField(default='INFO', max_length=30)),
                ('source', models.CharField(default='API Gateway', max_length=100)),
                ('attributes_json', models.TextField(default='{}')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
