# Generated by Django 6.0.4 on 2026-10-06 14:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0028_alertrecord_runbookrecord_servicedefinitionrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADRRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='ADR 027: Consolidate Settlement Reconciliation', max_length=255)),
                ('status', models.CharField(default='PROPOSED', max_length=30)),
                ('context', models.TextField(default='')),
                ('decision', models.TextField(default='')),
                ('consequences', models.TextField(default='')),
                ('author', models.CharField(default='Software Architect Agent', max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BuildArtifactRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_sha', models.CharField(default='sha_a1b2c3d', max_length=100)),
                ('artifact_name', models.CharField(default='artisan-core-build-v2.7', max_length=255)),
                ('environment', models.CharField(default='staging', max_length=50)),
                ('checksum_sha256', models.CharField(default='sha256_e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', max_length=100)),
                ('build_status', models.CharField(default='SUCCESS', max_length=30)),
                ('test_pass_rate_pct', models.FloatField(default=100.0)),
                ('security_scan_passed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CodeChangeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_file', models.CharField(default='backend/artisan_api/views.py', max_length=255)),
                ('summary', models.TextField(default='Minimal diff patch applied for safe error handling.')),
                ('diff_content', models.TextField(default='')),
                ('minimality_score', models.FloatField(default=9.5)),
                ('risk_score', models.IntegerField(default=15)),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CodeEntityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(default='code_backend_models', max_length=100, unique=True)),
                ('name', models.CharField(default='artisan_api.models', max_length=255)),
                ('entity_type', models.CharField(default='MODULE', max_length=50)),
                ('filepath', models.CharField(default='backend/artisan_api/models.py', max_length=255)),
                ('owner', models.CharField(default='Data Architecture Team', max_length=150)),
                ('language', models.CharField(default='Python/Django', max_length=50)),
                ('lines_of_code', models.IntegerField(default=2400)),
                ('complexity_score', models.IntegerField(default=15)),
                ('dependencies_json', models.TextField(default='[]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngineeringTaskRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.CharField(default='Engineering Task Goal', max_length=255)),
                ('assigned_agent', models.CharField(default='BackendEngineerAgent', max_length=100)),
                ('status', models.CharField(default='IN_PROGRESS', max_length=30)),
                ('affected_files_json', models.TextField(default='[]')),
                ('risk_score', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(default='v2.7.0', max_length=50)),
                ('environment', models.CharField(default='canary', max_length=50)),
                ('release_readiness_score', models.FloatField(default=98.0)),
                ('dora_metrics_json', models.TextField(default='{}')),
                ('status', models.CharField(default='STAGING', max_length=30)),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Requirement Definition', max_length=255)),
                ('raw_text', models.TextField(default='')),
                ('acceptance_criteria_json', models.TextField(default='[]')),
                ('affected_components_json', models.TextField(default='[]')),
                ('implementation_plan_json', models.TextField(default='[]')),
                ('risk_level', models.CharField(default='MEDIUM', max_length=30)),
                ('status', models.CharField(default='PARSED', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalDebtRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Refactor Duplicate View Logic', max_length=255)),
                ('component', models.CharField(default='artisan_api.views', max_length=150)),
                ('problem_description', models.TextField(default='Duplicate settlement reconciliation calculations.')),
                ('risk_score', models.IntegerField(default=25)),
                ('estimated_effort_hours', models.FloatField(default=3.0)),
                ('owner', models.CharField(default='FinOps & Architecture Team', max_length=150)),
                ('status', models.CharField(default='OPEN', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='test_order_creation_with_null_discount', max_length=255)),
                ('test_type', models.CharField(default='UNIT', max_length=50)),
                ('filepath', models.CharField(default='backend/artisan_api/tests.py', max_length=255)),
                ('code_body', models.TextField(default='')),
                ('is_flaky', models.BooleanField(default=False)),
                ('last_status', models.CharField(default='PASSED', max_length=30)),
                ('duration_ms', models.IntegerField(default=140)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CodeReviewRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_agent', models.CharField(default='AICodeReviewerAgent', max_length=100)),
                ('findings_json', models.TextField(default='[]')),
                ('security_passed', models.BooleanField(default=True)),
                ('quality_score', models.FloatField(default=98.5)),
                ('approval_status', models.CharField(default='APPROVED', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='artisan_api.codechangerecord')),
            ],
        ),
    ]
