# Generated by Django 6.0.4 on 2026-10-06 14:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0029_adrrecord_buildartifactrecord_codechangerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataContractRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='OrderCreatedContract', max_length=150)),
                ('source_service', models.CharField(default='MarketplaceAPI', max_length=100)),
                ('target_service', models.CharField(default='FinanceEngine', max_length=100)),
                ('schema_definition_json', models.JSONField(blank=True, default=dict)),
                ('quality_rules_json', models.JSONField(blank=True, default=dict)),
                ('freshness_sla_mins', models.IntegerField(default=10)),
                ('owner', models.CharField(default='Data Governance Office', max_length=150)),
                ('status', models.CharField(default='VERIFIED', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DataIncidentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_id', models.CharField(default='INC_DATA_901', max_length=100, unique=True)),
                ('severity', models.CharField(default='HIGH', max_length=30)),
                ('affected_dataset', models.CharField(default='inventory_reconciliation_feed', max_length=150)),
                ('pipeline_id', models.CharField(default='pipe_inv_sync', max_length=100)),
                ('symptoms', models.TextField(default='Warehouse inventory (100 units) contradicts Marketplace inventory (82 units).')),
                ('root_cause', models.TextField(default='Upstream API webhook dropped 18 cancellation events.')),
                ('recovery_plan', models.TextField(default='Replay cancellation CDC stream and re-reconcile stock balances.')),
                ('status', models.CharField(default='DETECTED', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DataLineageEdgeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_entity', models.CharField(default='raw_marketplace_orders', max_length=150)),
                ('destination_entity', models.CharField(default='curated_sales_analytics', max_length=150)),
                ('transformation_rule', models.TextField(default='Join with Customer 360 & Normalize Currency to INR')),
                ('version', models.CharField(default='v1.0', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DataProductRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Artisan Commerce Customer 360', max_length=150)),
                ('domain', models.CharField(default='Commerce', max_length=50)),
                ('owner', models.CharField(default='Customer Intelligence Lead', max_length=150)),
                ('version', models.CharField(default='v3.0', max_length=30)),
                ('freshness_sla_mins', models.IntegerField(default=30)),
                ('trust_score', models.FloatField(default=96.2)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('usage_count', models.IntegerField(default=1420)),
                ('status', models.CharField(default='PUBLISHED', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityCheckRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(default='canonical_inventory', max_length=150)),
                ('check_type', models.CharField(default='COMPLETENESS', max_length=50)),
                ('passed', models.BooleanField(default=True)),
                ('failed_records_count', models.IntegerField(default=0)),
                ('score', models.FloatField(default=98.5)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(default='src_pg_main', max_length=100, unique=True)),
                ('organization_id', models.CharField(default='org_artisan_crafts', max_length=100)),
                ('source_type', models.CharField(default='PostgreSQL', max_length=50)),
                ('source_name', models.CharField(default='Main ERP & Transactions DB', max_length=255)),
                ('owner', models.CharField(default='Data Platform Team', max_length=150)),
                ('connection_ref', models.CharField(default='postgresql://user:***@db.internal:5432/commerce_os', max_length=255)),
                ('ingestion_mode', models.CharField(default='CDC', max_length=30)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('freshness_expectation_mins', models.IntegerField(default=15)),
                ('data_classification', models.CharField(default='CONFIDENTIAL', max_length=50)),
                ('quality_score', models.FloatField(default=95.0)),
                ('status', models.CharField(default='HEALTHY', max_length=30)),
                ('last_successful_ingestion', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_failure', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJobRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(default='job_ingest_001', max_length=100, unique=True)),
                ('source_id', models.CharField(default='src_pg_main', max_length=100)),
                ('organization_id', models.CharField(default='org_artisan_crafts', max_length=100)),
                ('pipeline_id', models.CharField(default='pipe_orders_clean', max_length=100)),
                ('mode', models.CharField(default='BATCH', max_length=30)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('records_read', models.IntegerField(default=12500)),
                ('records_written', models.IntegerField(default=12495)),
                ('records_rejected', models.IntegerField(default=5)),
                ('bytes_processed', models.BigIntegerField(default=4500000)),
                ('checkpoint', models.CharField(default='ckpt_pos_12495', max_length=255)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('execution_version', models.CharField(default='v1.0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaRegistryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(default='canonical_orders', max_length=150)),
                ('version', models.CharField(default='v2.1', max_length=30)),
                ('owner', models.CharField(default='Data Engineering Team', max_length=150)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(default='sha256_schema_ord_v2.1', max_length=100)),
                ('detected_drift_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
