# Generated by Django 6.0.4 on 2026-10-06 18:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_api', '0030_datacontractrecord_dataincidentrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcessRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_id', models.CharField(default='proc_b2b_order_fulfillment', max_length=100, unique=True)),
                ('name', models.CharField(default='B2B Bulk Order Fulfillment & Settlement Process', max_length=255)),
                ('category', models.CharField(default='Commerce', max_length=50)),
                ('version', models.CharField(default='v2.0', max_length=30)),
                ('happy_path_json', models.JSONField(blank=True, default=list)),
                ('actual_variants_json', models.JSONField(blank=True, default=list)),
                ('automation_level', models.CharField(default='Level 3 Bounded Automation', max_length=50)),
                ('health_score', models.FloatField(default=92.5)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_id', models.CharField(default='CLM_001', max_length=100, unique=True)),
                ('question_id', models.CharField(default='Q_EU_EXPANSION_001', max_length=100)),
                ('statement', models.TextField(default='EU market demand for artisan sustainable gifts is estimated at €4.2 Billion in 2026.')),
                ('source_url', models.URLField(default='https://ec.europa.eu/eurostat/handicrafts-market-2026', max_length=500)),
                ('evidence_snippet', models.TextField(default='Page 14, Table 3: Sustainable craft imports grew 14.2% YoY.')),
                ('evidence_level', models.CharField(default='E4_PRIMARY', max_length=20)),
                ('confidence_score', models.FloatField(default=96.0)),
                ('status', models.CharField(default='VERIFIED', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EvidencePackRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_id', models.CharField(default='EVP_EU_2026', max_length=100, unique=True)),
                ('question_id', models.CharField(default='Q_EU_EXPANSION_001', max_length=100)),
                ('claims_json', models.JSONField(blank=True, default=list)),
                ('corroboration_count', models.IntegerField(default=5)),
                ('contradiction_count', models.IntegerField(default=0)),
                ('trust_score', models.FloatField(default=95.2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessBottleneckRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_id', models.CharField(default='proc_b2b_order_fulfillment', max_length=100)),
                ('bottleneck_step', models.CharField(default='Supplier Confirmation & Raw Material Check', max_length=150)),
                ('avg_wait_time_sec', models.IntegerField(default=115200)),
                ('failure_rate_pct', models.FloatField(default=14.5)),
                ('cost_impact_inr', models.FloatField(default=45000.0)),
                ('root_cause_summary', models.TextField(default='Manual phone follow-ups and lack of automated SMS/WhatsApp reminders.')),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDecisionReceiptRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(default='CASE_B2B_901', max_length=100)),
                ('decision', models.TextField(default='Deployed bounded automated supplier reminder and parallel inventory validation workflow.')),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('policy_version', models.CharField(default='POL_BOUNDED_WORKFLOW_v2', max_length=30)),
                ('actor', models.CharField(default='Process Intelligence Agent', max_length=100)),
                ('approved_by', models.CharField(default='Operations Manager', max_length=100)),
                ('status', models.CharField(default='VERIFIED', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEventRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(default='CASE_B2B_901', max_length=100)),
                ('process_id', models.CharField(default='proc_b2b_order_fulfillment', max_length=100)),
                ('step_name', models.CharField(default='Supplier Confirmation', max_length=150)),
                ('actor', models.CharField(default='Jaipur Supplier Network', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_sec', models.IntegerField(default=115200)),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStepRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_id', models.CharField(default='step_supplier_confirm', max_length=100)),
                ('process_id', models.CharField(default='proc_b2b_order_fulfillment', max_length=100)),
                ('step_name', models.CharField(default='Supplier Confirmation & Raw Material Check', max_length=150)),
                ('step_type', models.CharField(default='HUMAN', max_length=50)),
                ('avg_duration_sec', models.IntegerField(default=129600)),
                ('risk_level', models.CharField(default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchQuestionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(default='Q_EU_EXPANSION_001', max_length=100, unique=True)),
                ('objective', models.TextField(default='Should our artisan commerce platform expand into the European handmade gift market?')),
                ('depth_mode', models.CharField(default='DEEP', max_length=30)),
                ('time_budget_sec', models.IntegerField(default=120)),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('answer_summary', models.TextField(default='European handmade gift market exhibits 14.2% YoY growth with high demand for Jaipur terracotta and handloom silk.')),
                ('confidence_score', models.FloatField(default=94.5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchReportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(default='REP_EU_GIFTS_2026', max_length=100, unique=True)),
                ('title', models.CharField(default='European Handmade Gift Market Expansion Deep Research Report', max_length=255)),
                ('topic', models.CharField(default='Market Expansion', max_length=100)),
                ('executive_summary', models.TextField(default='High viability for European expansion with 14.2% demand growth in Germany and France.')),
                ('findings_json', models.JSONField(blank=True, default=dict)),
                ('contradictions_json', models.JSONField(blank=True, default=dict)),
                ('unknowns_json', models.JSONField(blank=True, default=dict)),
                ('version', models.CharField(default='v1.0', max_length=30)),
                ('status', models.CharField(default='PUBLISHED', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchSourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(default='src_eurostat_01', max_length=100, unique=True)),
                ('url', models.URLField(default='https://ec.europa.eu/eurostat/handicrafts-market-2026', max_length=500)),
                ('source_type', models.CharField(default='GOVERNMENT', max_length=50)),
                ('publisher', models.CharField(default='Eurostat Trade Directorate', max_length=200)),
                ('domain', models.CharField(default='ec.europa.eu', max_length=150)),
                ('authority_score', models.FloatField(default=95.0)),
                ('freshness_score', models.FloatField(default=92.0)),
                ('trust_classification', models.CharField(default='AUTHORITATIVE', max_length=30)),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchWatchlistRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_or_competitor', models.CharField(default='EU Import Tariffs & Craft Regulations', max_length=150)),
                ('frequency', models.CharField(default='DAILY', max_length=30)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowOptimizationProposalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Automate Supplier Reminders & Parallelize QC Checkpoint', max_length=255)),
                ('process_id', models.CharField(default='proc_b2b_order_fulfillment', max_length=100)),
                ('current_cycle_time_mins', models.IntegerField(default=2880)),
                ('proposed_cycle_time_mins', models.IntegerField(default=840)),
                ('estimated_roi_inr', models.FloatField(default=185000.0)),
                ('risk_assessment', models.CharField(default='LOW_RISK_REVERSIBLE', max_length=50)),
                ('status', models.CharField(default='APPROVED', max_length=30)),
            ],
        ),
    ]
